name = "CodecInflate64"
uuid = "6309b1aa-fc58-479c-8956-599a07234577"
authors = ["nhz2 <nhz2@cornell.edu>"]
version = "0.1.3"

[deps]
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
TranscodingStreams = "0.9, 0.10, 0.11"
julia = "1.6"
